### ISSUE TITLE
Missing Files Required to Compile

### ISSUE THREAD

**Issue by TheBambino** [brianide/BloodTithe#1]
All the files in the  commonground folder are not present.

**Comment by TheBambino** [comment]
Found in another repository.

**Comment by TheBambino** [comment]
Found in another repository.

**Comment by brianide** [comment]
The CommonGround sources are available in a nuget package, so you can get at them this way (on a fresh clone):
```bash
nuget restore
cp -r packages/CommonGround.Sources.0.1.0/content/CommonGround BloodTithe/
```
It's still a shitty workflow, admittedly, and I'm fairly certain it's an abuse of how nuget packages are supposed to work.

The reason for this goofy setup is that I don't want to have to distribute the CommonGround library code as a separate DLL, and I couldn't figure out a proper way to create the C# equivalent of a fat-JAR/JAR-with-dependencies. I'm sure there probably _is_ one (and I'd be delighted to hear about it), but .NET isn't my typical wheelhouse, so after putting several hours into trying to figure it out, I just settled on this, since it worked well enough at the time.

I'll add some build instructions to the documentation.
